"""Add Match model

Revision ID: fd5e57a826d3
Revises: 22a5b5bcb281
Create Date: 2024-12-12 11:33:45.061363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd5e57a826d3'
down_revision = '22a5b5bcb281'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('match')
    with op.batch_alter_table('Animal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('matched', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Animal', schema=None) as batch_op:
        batch_op.drop_column('matched')

    op.create_table('match',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('animal_id', sa.INTEGER(), nullable=False),
    sa.Column('matched', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['Animal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Match')
    # ### end Alembic commands ###
